### ISSUE TITLE
Let's add a Scratch compatible .moar.sb3 file format

### ISSUE THREAD

**Issue by ozramos** [MoarHaus/scratch-browser-snapshots#7]
This file format will hide all of snapshots in comments or through some other mechanism, making the active autosave the current Scratch Project. This will allow for the same project to be used either on Scratch or with Scratch forks

# Milestones
- [x] Ability to update a snapshot
- [x] Export snapshots as .json
- [x] Import snapshots from .json
- [x] Export all snapshots as `.moar.sb3`, just store the snapshots separately within the file
